### ISSUE TITLE
it2ul upload files faild

### ISSUE THREAD

**Issue by garywu520** [gnachman/iTerm2-shell-integration#3]
it2ul shows that there is no automatic carriage return after uploading the file. In fact, it has been stuck. After waiting for a long time, the error: tar: could not chdir to'Desktop/Python.pdf'

Platform: Mac/Linux

**Comment by garywu520** [comment]
After subsequent test, it was found that the small file upload of KB is ok, but such as 5m + size: *. MP3 or * .mp4 file upload will be attached, the TAR.GZ files around 100m are also. I hope to provide a solution, thank you.

**Comment by gnachman** [comment]
Please file an issue at https://iterm2.com/bugs and attach a debug log
